#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xafeaea66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x33ba5cd4, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x6c6c62f6, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0xa210a55a, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0x8aad5774, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0x6abbe5f9, __VMLINUX_SYMBOL_STR(blk_fetch_request) },
	{ 0xbd0fce40, __VMLINUX_SYMBOL_STR(__blk_end_request_all) },
	{ 0x2b25aa53, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0x4f3be27a, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0x89a2fd8f, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0xc2c8753d, __VMLINUX_SYMBOL_STR(bio_advance) },
	{ 0x9c074946, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0x8a4fa83b, __VMLINUX_SYMBOL_STR(__aeabi_llsr) },
	{ 0x5d776086, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0x1d6b01de, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0xf255570b, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x31e9a0cc, __VMLINUX_SYMBOL_STR(blk_queue_merge_bvec) },
	{ 0x8c3d610a, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x2e05020, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0xb120c745, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0x4dfb16d4, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0x4b72f0a, __VMLINUX_SYMBOL_STR(blk_queue_physical_block_size) },
	{ 0x9de88022, __VMLINUX_SYMBOL_STR(blk_init_queue) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x1c409a52, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0x5b72009f, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0x1475bf0d, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0xa14f58f7, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x7f00c37c, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0xa8daffc8, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0x4205ffd7, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0xb730b481, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0x12e3160b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xc55de604, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x6c1ce5ce, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc7ec6c27, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0xa1403523, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xe82c9c32, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x31de9183, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x83211609, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xa958ed4, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x76cf47f6, __VMLINUX_SYMBOL_STR(__aeabi_llsl) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xd1c9f0f8, __VMLINUX_SYMBOL_STR(osd_req_op_cls_response_data_pages) },
	{ 0x3f23ea15, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pagelist) },
	{ 0x6ed41be2, __VMLINUX_SYMBOL_STR(ceph_pagelist_append) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xe44f1f08, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0xfaec47a1, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0x2bb55ae, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0x77caa3cb, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0xed96a552, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0xeba65519, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0x4614e98c, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0x4a98e7a3, __VMLINUX_SYMBOL_STR(blk_end_request) },
	{ 0xbebd9d94, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0xe97e547, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0xaca1a3f0, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x996bdb64, __VMLINUX_SYMBOL_STR(_kstrtoul) },
	{ 0x9485eaef, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_event) },
	{ 0xfd5683b9, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible) },
	{ 0x2537696a, __VMLINUX_SYMBOL_STR(osd_req_op_watch_init) },
	{ 0xe7a43b8a, __VMLINUX_SYMBOL_STR(ceph_osdc_unregister_linger_request) },
	{ 0x5c937f8a, __VMLINUX_SYMBOL_STR(ceph_osdc_set_request_linger) },
	{ 0x23452d82, __VMLINUX_SYMBOL_STR(ceph_osdc_create_event) },
	{ 0x94839439, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0xfb4f3c97, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x34184afe, __VMLINUX_SYMBOL_STR(current_kernel_time) },
	{ 0x2fe14fb7, __VMLINUX_SYMBOL_STR(ceph_osdc_build_request) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xde266da8, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x20df2681, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0xe66163c4, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0xf4926eee, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0xe8475db0, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0xc8da207f, __VMLINUX_SYMBOL_STR(ceph_client_id) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x3acd0ee8, __VMLINUX_SYMBOL_STR(set_device_ro) },
	{ 0xe8f3f914, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x7d4e2276, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0x74d0b74c, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x22e1ae6f, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0x455293f6, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xab694444, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0x6a4837b8, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0x81f3afb, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x2fc73131, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xc145918, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0x36d68e33, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x1b9831c3, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0x9e81a13e, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0x197effcb, __VMLINUX_SYMBOL_STR(ceph_osdc_release_request) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xb9610059, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x588c32c0, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x84a3c035, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libceph";

