#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xafeaea66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xfbc3fc5c, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x1f9041b4, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x588c32c0, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9427374, __VMLINUX_SYMBOL_STR(dispc_request_irq) },
	{ 0xf88c3301, __VMLINUX_SYMBOL_STR(sg_init_table) },
	{ 0x93963a85, __VMLINUX_SYMBOL_STR(dss_feat_get_num_mgrs) },
	{ 0x9f823cea, __VMLINUX_SYMBOL_STR(dispc_mgr_is_enabled) },
	{ 0xeae40a12, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x3053390e, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0xbe8860a8, __VMLINUX_SYMBOL_STR(dispc_mgr_go_busy) },
	{ 0x1699dce5, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0x81206a4c, __VMLINUX_SYMBOL_STR(drm_framebuffer_reference) },
	{ 0xb9233201, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0xb6b46a7c, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xddbfe684, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0x65e59b74, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0xedd5fff7, __VMLINUX_SYMBOL_STR(dev_set_drvdata) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x1d405b73, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x9efc26a3, __VMLINUX_SYMBOL_STR(drm_flip_work_cleanup) },
	{ 0x436e9853, __VMLINUX_SYMBOL_STR(omap_dss_get_overlay_manager) },
	{ 0x64a22ff0, __VMLINUX_SYMBOL_STR(dispc_mgr_set_lcd_config) },
	{ 0xdb93b838, __VMLINUX_SYMBOL_STR(dispc_free_irq) },
	{ 0xd1664c96, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x986a3269, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0x1b7fd59, __VMLINUX_SYMBOL_STR(dispc_read_irqstatus) },
	{ 0x547ce898, __VMLINUX_SYMBOL_STR(dispc_read_irqenable) },
	{ 0xa35444e4, __VMLINUX_SYMBOL_STR(dispc_write_irqenable) },
	{ 0x2fcf0fec, __VMLINUX_SYMBOL_STR(drm_property_create_range) },
	{ 0x58c4a14a, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf7802486, __VMLINUX_SYMBOL_STR(__aeabi_uidivmod) },
	{ 0xed6d3f24, __VMLINUX_SYMBOL_STR(drm_plane_init) },
	{ 0xb891c351, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x6a57ab31, __VMLINUX_SYMBOL_STR(drm_gem_mmap_obj) },
	{ 0x22675997, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xee2bc2d0, __VMLINUX_SYMBOL_STR(omapdss_is_initialized) },
	{ 0x39775ac6, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0xf07e2c4a, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0x1ea132e, __VMLINUX_SYMBOL_STR(dispc_runtime_put) },
	{ 0x33ba5cd4, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0xa14f58f7, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x50d5612e, __VMLINUX_SYMBOL_STR(dispc_mgr_get_sync_lost_irq) },
	{ 0xd57c7d33, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x2457a658, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xb95beb55, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0x91296ba4, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x13717f44, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x5689afe7, __VMLINUX_SYMBOL_STR(dispc_ovl_enable) },
	{ 0x562a84ff, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset_size) },
	{ 0x2d2fbe9e, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x20b6e8d2, __VMLINUX_SYMBOL_STR(__pv_phys_offset) },
	{ 0xee99c075, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x56bc2f15, __VMLINUX_SYMBOL_STR(dispc_ovl_set_channel_out) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x7cbe8095, __VMLINUX_SYMBOL_STR(dispc_mgr_set_timings) },
	{ 0xd791ff5f, __VMLINUX_SYMBOL_STR(drm_vblank_count) },
	{ 0x4c511235, __VMLINUX_SYMBOL_STR(drm_edid_is_valid) },
	{ 0x3277f4a, __VMLINUX_SYMBOL_STR(omap_dss_put_device) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x477bf5eb, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0x60055baa, __VMLINUX_SYMBOL_STR(dispc_mgr_get_vsync_irq) },
	{ 0xdb5a5852, __VMLINUX_SYMBOL_STR(drm_flip_work_queue) },
	{ 0xacebd2cd, __VMLINUX_SYMBOL_STR(drm_handle_vblank) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0xc145918, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xa07053c9, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x83dc1138, __VMLINUX_SYMBOL_STR(drm_fb_helper_restore_fbdev_mode) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xfe40bf95, __VMLINUX_SYMBOL_STR(dss_feat_get_num_ovls) },
	{ 0x138f003f, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x9c7e5296, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x970e32d, __VMLINUX_SYMBOL_STR(drm_mode_set_name) },
	{ 0xb7170839, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xc1b4d63d, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x8f7df3a7, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0xb15b88b3, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x6b34432c, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0x711f5a16, __VMLINUX_SYMBOL_STR(omapdss_find_mgr_from_display) },
	{ 0xedccd5e5, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x9555b038, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x61aada0, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0xcbe24c28, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x3e6bcc48, __VMLINUX_SYMBOL_STR(omap_dss_get_next_device) },
	{ 0x14f73b95, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0x2d770676, __VMLINUX_SYMBOL_STR(dispc_mgr_go) },
	{ 0x3dab2fea, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x12e3160b, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x4e9d8149, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0xddc6b8f8, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0xbe843ee7, __VMLINUX_SYMBOL_STR(platform_get_resource) },
	{ 0x867a41ac, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xcabab563, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xe6a286db, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x3082a0b3, __VMLINUX_SYMBOL_STR(dss_feat_get_supported_color_modes) },
	{ 0xd6b8e852, __VMLINUX_SYMBOL_STR(request_threaded_irq) },
	{ 0x768af748, __VMLINUX_SYMBOL_STR(drm_sysfs_connector_remove) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0xbd61115c, __VMLINUX_SYMBOL_STR(fput) },
	{ 0x8c48c068, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0xcce4d6cb, __VMLINUX_SYMBOL_STR(drm_platform_init) },
	{ 0x9745d638, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xbc710d40, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0xb70e8b15, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x32eebf8d, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0x85b03ea4, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0xe7e15910, __VMLINUX_SYMBOL_STR(dispc_clear_irqstatus) },
	{ 0x97aaa12, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0xcdd158d, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x555d737f, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x988136c3, __VMLINUX_SYMBOL_STR(drm_framebuffer_remove) },
	{ 0xfa1479dc, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xce748774, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x7a973ad5, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0xe6af4ccb, __VMLINUX_SYMBOL_STR(drm_mode_create) },
	{ 0xcd95ae63, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x2c098c08, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x92ec5d1b, __VMLINUX_SYMBOL_STR(dispc_mgr_enable) },
	{ 0x2b5acefb, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0xfed80d73, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0x9793c93a, __VMLINUX_SYMBOL_STR(dispc_mgr_setup) },
	{ 0xfd5f24cc, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x6607f92, __VMLINUX_SYMBOL_STR(dss_feat_get_supported_outputs) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x6e80ac0b, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x99123359, __VMLINUX_SYMBOL_STR(drm_gem_private_object_init) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0x2c535967, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x1a00746d, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0xc2165d85, __VMLINUX_SYMBOL_STR(__arm_iounmap) },
	{ 0xbe8fb90c, __VMLINUX_SYMBOL_STR(dispc_mgr_get_framedone_irq) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0xeddf9397, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x2a0dbb53, __VMLINUX_SYMBOL_STR(drm_sysfs_connector_add) },
	{ 0x32a30e22, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x76f837fd, __VMLINUX_SYMBOL_STR(drm_fb_helper_hotplug_event) },
	{ 0xec527fc, __VMLINUX_SYMBOL_STR(drm_flip_work_commit) },
	{ 0xbafeee36, __VMLINUX_SYMBOL_STR(dispc_runtime_get) },
	{ 0x84a3c035, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x88ab69ca, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xbf1aca73, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x24ddfb61, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0xe2ba6b5d, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x84aa9ea7, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xb0c568c1, __VMLINUX_SYMBOL_STR(vm_insert_mixed) },
	{ 0x70e39dae, __VMLINUX_SYMBOL_STR(dss_uninstall_mgr_ops) },
	{ 0x9f9fb0d1, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xcacda960, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0xd1a18886, __VMLINUX_SYMBOL_STR(unmap_mapping_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xcb2ec95, __VMLINUX_SYMBOL_STR(omap_dss_get_device) },
	{ 0x9d42d7cc, __VMLINUX_SYMBOL_STR(dma_supported) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0xc7d695da, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0xe12dc3b9, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0xb3c543fe, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x5a27d46a, __VMLINUX_SYMBOL_STR(dma_buf_export_named) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x13cdaadb, __VMLINUX_SYMBOL_STR(drm_flip_work_init) },
	{ 0xe2ef4525, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xfb961d14, __VMLINUX_SYMBOL_STR(__arm_ioremap) },
	{ 0x9cd60539, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x826846fe, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x9d9204ec, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xb2aa5b05, __VMLINUX_SYMBOL_STR(platform_get_irq) },
	{ 0xce92ec84, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x4969ba32, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xb3e81f85, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0x8287b9fa, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x498dcb5e, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x19aa9b2a, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_init) },
	{ 0x71658a05, __VMLINUX_SYMBOL_STR(dispc_ovl_setup) },
	{ 0x76cfd9df, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x71fe4ac1, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0xac8f37b2, __VMLINUX_SYMBOL_STR(outer_cache) },
	{ 0xbae18164, __VMLINUX_SYMBOL_STR(dss_install_mgr_ops) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x4a5e046c, __VMLINUX_SYMBOL_STR(dev_get_drvdata) },
	{ 0x5b81fb4d, __VMLINUX_SYMBOL_STR(omapdss_find_output_from_display) },
	{ 0x6b57ff81, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x2f7ead9a, __VMLINUX_SYMBOL_STR(drm_mm_dump_table) },
	{ 0x5821012a, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0xc459e850, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0xd8cd4130, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0xf20dabd8, __VMLINUX_SYMBOL_STR(free_irq) },
	{ 0x42dec477, __VMLINUX_SYMBOL_STR(drm_property_create_bitmask) },
	{ 0x9bc55511, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0xf4f0fbb9, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_fini) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x8f42ffa8, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0x7307b5b7, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=omapdss";

