#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xafeaea66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf3017e21, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0xdbcff9be, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0x585aefb7, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0x7097378c, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xfcc6d628, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0x4170823e, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0xe9af7935, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0x128f186c, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0xfb42a2ea, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xf8098221, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0xe01f37ac, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0xe1227b3c, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0xc9226478, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0x26262aa2, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0xf6ffa7d6, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xaed4f65e, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0x41178409, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0xd78e6f89, __VMLINUX_SYMBOL_STR(security_skb_classify_flow) },
	{ 0xab8ec2f8, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0xf2ac65ab, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0x99c7afe3, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0x3df7b362, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0x515d8a89, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0x618a22ad, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0x7e605ece, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x40cfac6a, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0x6cd7b532, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0x4dc19683, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0x69b66a01, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x8ffdab87, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0x9b566e75, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xb36060f1, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x6595f14c, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xaf66fcb6, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0xe57320e9, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x4bcba189, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0x92c1ba75, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0xc6f058c1, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0x2deda4a1, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0xe89b9af9, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0xd98da629, __VMLINUX_SYMBOL_STR(inet_csk_search_req) },
	{ 0x8e9298c, __VMLINUX_SYMBOL_STR(inet_csk_delete_keepalive_timer) },
	{ 0xf5c37c25, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0x36d68e33, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x53e69779, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x9a5ba741, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x4f539b1c, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0x61ccbf81, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x8d8fda8b, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0x8f663a0c, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0x9a123b7, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0xc2dc962c, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xa20ce1b8, __VMLINUX_SYMBOL_STR(net_msg_warn) },
	{ 0x5f0893e6, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0xfec70d56, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0xcb93d888, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0x4f13d9b0, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0x13bb1479, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0x3f50f329, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0xc65b8a24, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0x58020f8b, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0xadaa2a5c, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0xb9610059, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x5b4ce81, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x160a4e6d, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0x1bc535e0, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xadde60d9, __VMLINUX_SYMBOL_STR(__ip_route_output_key) },
	{ 0x816233bb, __VMLINUX_SYMBOL_STR(sk_release_kernel) },
	{ 0x96ff773c, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xf04193ae, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x24560395, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x9e3e7c1c, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0xe26012bc, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x964f01a7, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0x44fbb888, __VMLINUX_SYMBOL_STR(__inet_hash_nolisten) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xabc67d4a, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0xc5b4a6ed, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0x90f528db, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xf1dc5b20, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0xec15a41c, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0x53bffe04, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0x29db5f67, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0x5e9877ed, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0xfe981c06, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0xedf30e19, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x74bb1f2b, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x28e1d223, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0xef87cc78, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0xc18f0135, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0x570bc1af, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x880e294, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x5c683d31, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0xc9d49329, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0xc673eecd, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0x3b953ba8, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";

