#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xafeaea66, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2dce8386, __VMLINUX_SYMBOL_STR(register_netdevice) },
	{ 0x588c32c0, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0xeeb5358c, __VMLINUX_SYMBOL_STR(mrp_uninit_applicant) },
	{ 0xc726275a, __VMLINUX_SYMBOL_STR(dev_change_flags) },
	{ 0x6dd826f8, __VMLINUX_SYMBOL_STR(dev_mc_unsync) },
	{ 0x9374b036, __VMLINUX_SYMBOL_STR(mrp_request_leave) },
	{ 0x28a74768, __VMLINUX_SYMBOL_STR(single_open) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xdfe10668, __VMLINUX_SYMBOL_STR(garp_uninit_applicant) },
	{ 0x7bfe8947, __VMLINUX_SYMBOL_STR(vlan_dev_vlan_id) },
	{ 0xa9f145d8, __VMLINUX_SYMBOL_STR(dev_uc_add) },
	{ 0x6fc55845, __VMLINUX_SYMBOL_STR(single_release) },
	{ 0xd0d009b6, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0xded94d6a, __VMLINUX_SYMBOL_STR(garp_request_join) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0x74772569, __VMLINUX_SYMBOL_STR(vlan_uses_dev) },
	{ 0x9cf999e4, __VMLINUX_SYMBOL_STR(netif_carrier_on) },
	{ 0xd3f57a2, __VMLINUX_SYMBOL_STR(_find_next_bit_le) },
	{ 0x22675997, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0x83595ae3, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0x212737b8, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0x50c89f23, __VMLINUX_SYMBOL_STR(__alloc_percpu) },
	{ 0x44d5f842, __VMLINUX_SYMBOL_STR(dev_set_allmulti) },
	{ 0x8571a3bb, __VMLINUX_SYMBOL_STR(vlan_vid_del) },
	{ 0x16690f7, __VMLINUX_SYMBOL_STR(call_netdevice_notifiers) },
	{ 0x48b88ca1, __VMLINUX_SYMBOL_STR(linkwatch_fire_event) },
	{ 0xd7a08da, __VMLINUX_SYMBOL_STR(vlan_vid_add) },
	{ 0xbe4b6941, __VMLINUX_SYMBOL_STR(__netpoll_setup) },
	{ 0x76e4aa46, __VMLINUX_SYMBOL_STR(garp_init_applicant) },
	{ 0xf1e5de86, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0xf175f5da, __VMLINUX_SYMBOL_STR(proc_remove) },
	{ 0xbe137592, __VMLINUX_SYMBOL_STR(vlan_ioctl_set) },
	{ 0x4efda18e, __VMLINUX_SYMBOL_STR(netpoll_send_skb_on_dev) },
	{ 0xa0d8ad94, __VMLINUX_SYMBOL_STR(PDE_DATA) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xe57320e9, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x9fdecc31, __VMLINUX_SYMBOL_STR(unregister_netdevice_many) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xd3721f85, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{        0, __VMLINUX_SYMBOL_STR(ns_capable) },
	{ 0xb3028abd, __VMLINUX_SYMBOL_STR(__netpoll_free_async) },
	{ 0x94db11e0, __VMLINUX_SYMBOL_STR(__ethtool_get_settings) },
	{ 0xb11bc31e, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0x328a05f1, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x5d35ed94, __VMLINUX_SYMBOL_STR(garp_register_application) },
	{ 0x462bba8f, __VMLINUX_SYMBOL_STR(nla_put) },
	{ 0x2d121a89, __VMLINUX_SYMBOL_STR(netdev_upper_dev_unlink) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0xa08ebea8, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0x3bd146a2, __VMLINUX_SYMBOL_STR(proc_mkdir_data) },
	{ 0xd6b3fa4f, __VMLINUX_SYMBOL_STR(seq_release_net) },
	{ 0xd927b959, __VMLINUX_SYMBOL_STR(netif_stacked_transfer_operstate) },
	{ 0xd6ace7da, __VMLINUX_SYMBOL_STR(rtnl_link_unregister) },
	{ 0x5e241c17, __VMLINUX_SYMBOL_STR(__dev_get_by_index) },
	{ 0x7087070f, __VMLINUX_SYMBOL_STR(garp_request_leave) },
	{ 0x347013de, __VMLINUX_SYMBOL_STR(nla_validate) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x4a7c0440, __VMLINUX_SYMBOL_STR(arp_find) },
	{ 0x7c62d042, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0x5bcd2d3e, __VMLINUX_SYMBOL_STR(eth_header_parse) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x78d6206d, __VMLINUX_SYMBOL_STR(alloc_netdev_mqs) },
	{ 0xe26012bc, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x5de36b10, __VMLINUX_SYMBOL_STR(mrp_init_applicant) },
	{ 0xbe333b0d, __VMLINUX_SYMBOL_STR(netdev_upper_dev_link) },
	{ 0xa9345709, __VMLINUX_SYMBOL_STR(ether_setup) },
	{ 0x4a8d84d2, __VMLINUX_SYMBOL_STR(dev_uc_unsync) },
	{ 0xa08d07f0, __VMLINUX_SYMBOL_STR(__dev_get_by_name) },
	{ 0x84a3c035, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x6f7f622, __VMLINUX_SYMBOL_STR(garp_unregister_application) },
	{ 0x1176e07f, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xc598653, __VMLINUX_SYMBOL_STR(unregister_netdevice_queue) },
	{ 0xad4b6fa7, __VMLINUX_SYMBOL_STR(netdev_warn) },
	{ 0x80c381a9, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0xe9ed9ab3, __VMLINUX_SYMBOL_STR(eth_validate_addr) },
	{ 0x2b422ae0, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0x79582ab9, __VMLINUX_SYMBOL_STR(dev_set_promiscuity) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa15522c4, __VMLINUX_SYMBOL_STR(seq_open_net) },
	{ 0x34105a0f, __VMLINUX_SYMBOL_STR(mrp_register_application) },
	{ 0x686b8e76, __VMLINUX_SYMBOL_STR(rtnl_link_register) },
	{ 0x94fab9ae, __VMLINUX_SYMBOL_STR(dev_uc_del) },
	{ 0xc1eca0f5, __VMLINUX_SYMBOL_STR(dev_uc_sync) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xd869cfe8, __VMLINUX_SYMBOL_STR(netdev_update_features) },
	{ 0x85670f1d, __VMLINUX_SYMBOL_STR(rtnl_is_locked) },
	{ 0xbebee444, __VMLINUX_SYMBOL_STR(dev_queue_xmit) },
	{ 0x25b6f498, __VMLINUX_SYMBOL_STR(mrp_unregister_application) },
	{ 0x3aeac4ff, __VMLINUX_SYMBOL_STR(mrp_request_join) },
	{ 0x4ad9f481, __VMLINUX_SYMBOL_STR(dev_mc_sync) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0x2c5be136, __VMLINUX_SYMBOL_STR(dev_get_stats) },
	{ 0xdad02b26, __VMLINUX_SYMBOL_STR(dev_set_mtu) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=mrp,garp";


MODULE_INFO(srcversion, "0CF73ED0ECB12A0C73624CB");
